/*
 * The app catalogue.
 *
 * `apps/manifest.json` is the index: everything the Store list and the Updates
 * panel need, in one fetch. Per-app manifests are fetched only when somebody
 * opens an app page or installs it.
 *
 * That split is why the index carries versions. Without them the Updates panel
 * would have to fetch one manifest per installed package on every connect --
 * thirty apps is thirty round-trips before anything can be drawn. The obvious
 * risk is the two files drifting apart, and that is removed structurally rather
 * than by discipline: `apps/manifest.json` is generated by
 * tools/build_catalog.py from the per-app manifests, so it cannot disagree with
 * them.
 *
 * ## Channels
 *
 * A package may publish more than one build -- see channel.js for why exactly
 * one of them does. This module is where that ends: loadCatalog() resolves every
 * entry to the chosen channel's build, and loadManifest() folds that build into
 * the manifest, so everything downstream sees one version of one package and
 * nothing else in the page has to carry the idea of a channel at all.
 */

import { DEFAULT_CHANNEL, resolveChannel } from './channel.js';

export const CATALOG_URL = 'apps/manifest.json';

export class CatalogError extends Error {}

let cached = null;
let cachedChannel = null;
const manifests = new Map();

async function fetchJson(url, what) {
  let response;
  try {
    response = await fetch(url, { cache: 'no-cache' });
  } catch (error) {
    throw new CatalogError(`could not load ${what}: ${error.message}`);
  }
  if (!response.ok) {
    throw new CatalogError(`could not load ${what}: HTTP ${response.status}`);
  }
  try {
    return await response.json();
  } catch (error) {
    throw new CatalogError(`${what} is not valid JSON: ${error.message}`);
  }
}

/**
 * The catalogue index, fetched once per page load, resolved to one channel.
 *
 * Resolving here is the whole of what makes channels cheap. Every entry that
 * leaves this function has a single `version`, `bytes`, `maxFile` and `deps`,
 * exactly as it did before there were channels -- so the Store, the Updates
 * panel, the dependency resolver and the installer never learned about them and
 * cannot disagree with each other about which build is being talked about.
 *
 * The channel is remembered alongside the cache. Changing it has to refetch,
 * because what is cached is one channel's answer and not the raw index.
 */
export async function loadCatalog(channel = DEFAULT_CHANNEL) {
  if (cached && cachedChannel === channel) return cached;

  const raw = await fetchJson(CATALOG_URL, 'the app catalogue');
  if (!Array.isArray(raw.apps)) {
    throw new CatalogError('the app catalogue has no "apps" list');
  }

  const byId = new Map();
  const apps = [];
  for (const app of raw.apps) {
    if (!app.id || !app.dir) {
      throw new CatalogError('a catalogue entry is missing its id or directory');
    }
    if (byId.has(app.id)) {
      throw new CatalogError(`"${app.id}" appears twice in the catalogue`);
    }
    const resolved = resolveChannel(app, channel);
    byId.set(app.id, resolved);
    apps.push(resolved);
  }

  cachedChannel = channel;
  cached = {
    schema: raw.schema,
    revision: raw.revision,
    channel,
    categories: raw.categories || [],
    apps,
    byId,
  };
  return cached;
}

/**
 * Fold a package's chosen build into its manifest.
 *
 * A build inherits the whole manifest and overrides what it names, so the parts
 * that do not change between builds -- the name, the actions, the summary --
 * are written once. What a build almost always does override is
 * `dependencies`: that is the field that describes the build rather than the
 * package, and getting it from the wrong build is how somebody ends up
 * installing the C libraries for a version that does not use them.
 */
export function resolveBuild(manifest, version) {
  if (!manifest.builds) return manifest;

  const build = manifest.builds[version];
  if (!build) {
    throw new CatalogError(
      `${manifest.id} has no build ${version}; the catalogue index and `
      + `apps/${manifest.id}/manifest.json disagree, so run tools/build_catalog.py`);
  }

  const resolved = { ...manifest, ...build, version };
  delete resolved.builds;
  delete resolved.channels;
  return resolved;
}

/** One package's full manifest, fetched on demand and remembered. */
export async function loadManifest(catalog, id) {
  const key = `${catalog.channel || DEFAULT_CHANNEL}/${id}`;
  if (manifests.has(key)) return manifests.get(key);

  const entry = catalog.byId.get(id);
  if (!entry) throw new CatalogError(`"${id}" is not in the catalogue`);

  const raw = await fetchJson(
    `apps/${entry.dir}/manifest.json`, `the manifest for ${entry.name}`);

  if (raw.id !== id) {
    throw new CatalogError(
      `apps/${entry.dir}/manifest.json calls itself "${raw.id}", `
      + `but the catalogue lists it as "${id}"`);
  }

  const manifest = resolveBuild(raw, entry.version);
  if (manifest.version !== entry.version) {
    /*
     * Generated index versus hand-written manifest. If these disagree the
     * generator has not been run, and every version comparison below is
     * untrustworthy -- so say so rather than picking one.
     */
    throw new CatalogError(
      `${entry.name} is ${manifest.version} in its manifest but `
      + `${entry.version} in the catalogue index; run tools/build_catalog.py`);
  }

  manifests.set(key, manifest);
  return manifest;
}

/**
 * Fetch one of a package's payload files.
 *
 * From the build's directory, which for a package with channels is not the
 * package's own -- `builds/2.0.0/BLUE.8xp` rather than `BLUE.8xp`. The manifest
 * still names the file the same way whichever build it is, so nothing above
 * here has to know which one it is holding.
 */
export async function loadFile(catalog, id, path) {
  const entry = catalog.byId.get(id);
  if (!entry) throw new CatalogError(`"${id}" is not in the catalogue`);

  /* Payload paths come from a manifest, so they are ours -- but they still
   * address a URL, and one containing ".." would reach outside the package. */
  if (path.includes('..') || path.startsWith('/')) {
    throw new CatalogError(`"${path}" is not a valid file name for a package`);
  }

  const url = `apps/${entry.files || entry.dir}/${path}`;
  const response = await fetch(url, { cache: 'no-cache' });
  if (!response.ok) {
    throw new CatalogError(`${entry.name} is missing ${path} (HTTP ${response.status})`);
  }
  return new Uint8Array(await response.arrayBuffer());
}

/**
 * The packages the Store may offer.
 *
 * A disabled package is still in the index and still a package: one already on
 * a calculator keeps its name in the Device panel and its version in Updates,
 * and anything depending on it still resolves. What it loses is the shop
 * window. That is the whole difference between disabling a package and taking
 * it out of apps/ -- the second orphans every calculator that already has it.
 *
 * `hidden` puts them back in the window, for somebody who has turned developer
 * options on -- see developer.js. It is a parameter rather than something read
 * from storage in here, so these two stay functions of what they are given.
 */
export function listable(catalog, { hidden = false } = {}) {
  return hidden ? catalog.apps : catalog.apps.filter((app) => !app.disabled);
}

export function search(catalog, query, { hidden = false } = {}) {
  const apps = listable(catalog, { hidden });
  const needle = query.trim().toLowerCase();
  if (!needle) return apps;
  return apps.filter((app) =>
    app.name.toLowerCase().includes(needle)
    || app.id.includes(needle)
    || (app.summary || '').toLowerCase().includes(needle));
}

/** Forget everything fetched so far, so the next load picks up a new channel. */
export function reset() {
  cached = null;
  cachedChannel = null;
  manifests.clear();
}
