/*
 * The app catalogue.
 *
 * `apps/manifest.json` is the index: everything the Store list and the Updates
 * panel need, in one fetch. Per-app manifests are fetched only when somebody
 * opens an app page or installs it.
 *
 * That split is why the index carries versions. Without them the Updates panel
 * would have to fetch one manifest per installed package on every connect --
 * thirty apps is thirty round-trips before anything can be drawn. The obvious
 * risk is the two files drifting apart, and that is removed structurally rather
 * than by discipline: `apps/manifest.json` is generated by
 * tools/build_catalog.py from the per-app manifests, so it cannot disagree with
 * them.
 */

export const CATALOG_URL = 'apps/manifest.json';

export class CatalogError extends Error {}

let cached = null;
const manifests = new Map();

async function fetchJson(url, what) {
  let response;
  try {
    response = await fetch(url, { cache: 'no-cache' });
  } catch (error) {
    throw new CatalogError(`could not load ${what}: ${error.message}`);
  }
  if (!response.ok) {
    throw new CatalogError(`could not load ${what}: HTTP ${response.status}`);
  }
  try {
    return await response.json();
  } catch (error) {
    throw new CatalogError(`${what} is not valid JSON: ${error.message}`);
  }
}

/** The catalogue index, fetched once per page load. */
export async function loadCatalog() {
  if (cached) return cached;

  const raw = await fetchJson(CATALOG_URL, 'the app catalogue');
  if (!Array.isArray(raw.apps)) {
    throw new CatalogError('the app catalogue has no "apps" list');
  }

  const byId = new Map();
  for (const app of raw.apps) {
    if (!app.id || !app.dir) {
      throw new CatalogError('a catalogue entry is missing its id or directory');
    }
    if (byId.has(app.id)) {
      throw new CatalogError(`"${app.id}" appears twice in the catalogue`);
    }
    byId.set(app.id, app);
  }

  cached = {
    schema: raw.schema,
    revision: raw.revision,
    categories: raw.categories || [],
    apps: raw.apps,
    byId,
  };
  return cached;
}

/** One package's full manifest, fetched on demand and remembered. */
export async function loadManifest(catalog, id) {
  if (manifests.has(id)) return manifests.get(id);

  const entry = catalog.byId.get(id);
  if (!entry) throw new CatalogError(`"${id}" is not in the catalogue`);

  const manifest = await fetchJson(
    `apps/${entry.dir}/manifest.json`, `the manifest for ${entry.name}`);

  if (manifest.id !== id) {
    throw new CatalogError(
      `apps/${entry.dir}/manifest.json calls itself "${manifest.id}", `
      + `but the catalogue lists it as "${id}"`);
  }
  if (manifest.version !== entry.version) {
    /*
     * Generated index versus hand-written manifest. If these disagree the
     * generator has not been run, and every version comparison below is
     * untrustworthy -- so say so rather than picking one.
     */
    throw new CatalogError(
      `${entry.name} is ${manifest.version} in its manifest but `
      + `${entry.version} in the catalogue index; run tools/build_catalog.py`);
  }

  manifests.set(id, manifest);
  return manifest;
}

/** Fetch one of a package's payload files. */
export async function loadFile(catalog, id, path) {
  const entry = catalog.byId.get(id);
  if (!entry) throw new CatalogError(`"${id}" is not in the catalogue`);

  /* Payload paths come from a manifest, so they are ours -- but they still
   * address a URL, and one containing ".." would reach outside the package. */
  if (path.includes('..') || path.startsWith('/')) {
    throw new CatalogError(`"${path}" is not a valid file name for a package`);
  }

  const url = `apps/${entry.dir}/${path}`;
  const response = await fetch(url, { cache: 'no-cache' });
  if (!response.ok) {
    throw new CatalogError(`${entry.name} is missing ${path} (HTTP ${response.status})`);
  }
  return new Uint8Array(await response.arrayBuffer());
}

/**
 * The packages the Store may offer.
 *
 * A disabled package is still in the index and still a package: one already on
 * a calculator keeps its name in the Device panel and its version in Updates,
 * and anything depending on it still resolves. What it loses is the shop
 * window. That is the whole difference between disabling a package and taking
 * it out of apps/ -- the second orphans every calculator that already has it.
 */
export function listable(catalog) {
  return catalog.apps.filter((app) => !app.disabled);
}

export function search(catalog, query) {
  const apps = listable(catalog);
  const needle = query.trim().toLowerCase();
  if (!needle) return apps;
  return apps.filter((app) =>
    app.name.toLowerCase().includes(needle)
    || app.id.includes(needle)
    || (app.summary || '').toLowerCase().includes(needle));
}

/** Test seam: forget everything fetched so far. */
export function reset() {
  cached = null;
  manifests.clear();
}
